name: Python validation

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  python-validation:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        name: Checkout source code

      - name: Lint Code Base
        uses: github/super-linter@v3
        env:
          VALIDATE_PYTHON: true
          VALIDATE_PYTHON_PYLINT: true
          VALIDATE_PYTHON_BLACK: true
          FILTER_REGEX_INCLUDE: "src/*.py"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
